// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");

function findSmallestIndex(arr) {
  var smallestElement = Caml_array.caml_array_get(arr, 0);
  var smallestIndex = 0;
  for(var i = 1 ,i_finish = arr.length; i <= i_finish; ++i){
    if (Caml_array.caml_array_get(arr, i) < smallestElement) {
      smallestElement = Caml_array.caml_array_get(arr, i);
      smallestIndex = i;
    }
    
  }
  return smallestIndex;
}

function selectionSort(arr) {
  var sortedArray = /* array */[];
  for(var i = 0 ,i_finish = arr.length; i <= i_finish; ++i){
    var smallestIndex = findSmallestIndex(arr);
    Caml_array.caml_array_get($$Array.sub(arr, smallestIndex, 1), 0);
  }
  return sortedArray;
}

exports.findSmallestIndex = findSmallestIndex;
exports.selectionSort = selectionSort;
/* No side effect */
