// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';


var example = /* :: */[
  10,
  /* :: */[
    11,
    /* :: */[
      12,
      /* [] */0
    ]
  ]
];

console.log(example);

exports.example = example;
/*  Not a pure module */
