// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Belt_List = require("bs-platform/lib/js/belt_List.js");

var items = /* :: */[
  10,
  /* :: */[
    11,
    /* :: */[
      12,
      /* :: */[
        13,
        /* :: */[
          14,
          /* :: */[
            15,
            /* :: */[
              16,
              /* [] */0
            ]
          ]
        ]
      ]
    ]
  ]
];

function sqrtPlusOne(x) {
  return Math.sqrt(x + 1.0);
}

var roots = Belt_List.makeBy(5, sqrtPlusOne);

var taken3 = Belt_List.take(items, 3);

var dropped3 = Belt_List.drop(items, 3);

var badTake = Belt_List.take(items, 10);

var result = Belt_List.splitAt(items, 3);

if (result !== undefined) {
  var match = result;
  console.log(match[0]);
  console.log(match[1]);
} else {
  console.log("None");
}

var optElement = Belt_List.get(items, 3);

var badOptElement = Belt_List.get(items, 10);

var element = Belt_List.getExn(items, 3);

var badElement = Belt_List.getExn(items, 10);

exports.items = items;
exports.sqrtPlusOne = sqrtPlusOne;
exports.roots = roots;
exports.taken3 = taken3;
exports.dropped3 = dropped3;
exports.badTake = badTake;
exports.result = result;
exports.optElement = optElement;
exports.badOptElement = badOptElement;
exports.element = element;
exports.badElement = badElement;
/* roots Not a pure module */
