// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Js_math = require("bs-platform/lib/js/js_math.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");

function binary_search(list, item) {
  var low = 0;
  var high = list.length - 1 | 0;
  while(low <= high) {
    var midFloat = (low + high | 0) / 2 | 0;
    var mid = Js_math.floor(midFloat);
    var guess = Caml_array.caml_array_get(list, mid);
    if (guess !== item) {
      if (guess > item) {
        high = mid - 1 | 0;
      } else {
        low = mid + 1 | 0;
      }
    }
    
  };
  return undefined;
}

exports.binary_search = binary_search;
/* No side effect */
