// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Js_math = require("bs-platform/lib/js/js_math.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function binary_search(list, item) {
  var low = 0;
  var high = list.length - 1 | 0;
  while(low <= high) {
    var midFloat = (low + high | 0) / 2 | 0;
    var mid = Js_math.floor(midFloat);
    var guess = Caml_array.caml_array_get(list, mid);
    var match = guess !== item;
    if (match) {
      low = mid + 1 | 0;
    }
    var match$1 = guess > item;
    if (match$1) {
      high = mid - 1 | 0;
    } else {
      throw [
            Caml_builtin_exceptions.match_failure,
            /* tuple */[
              "binary_search.re",
              22,
              4
            ]
          ];
    }
  };
  return undefined;
}

var testArray = /* array */[
  1,
  4,
  5,
  12,
  231,
  2,
  3,
  4
];

console.log(binary_search(testArray, 2));

exports.binary_search = binary_search;
exports.testArray = testArray;
/*  Not a pure module */
