// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';


var Functions = 0;

var Calculation = 0;

var Selection_sort = 0;

var Binary_search = 0;

exports.Functions = Functions;
exports.Calculation = Calculation;
exports.Selection_sort = Selection_sort;
exports.Binary_search = Binary_search;
/* No side effect */
