// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';


var MyBelt = 0;

var ShirtSize = 0;

var BeltExamples = 0;

var StringOfColor = 0;

var Functions = 0;

var Calculation = 0;

var Selection_sort = 0;

var Binary_search = 0;

exports.MyBelt = MyBelt;
exports.ShirtSize = ShirtSize;
exports.BeltExamples = BeltExamples;
exports.StringOfColor = StringOfColor;
exports.Functions = Functions;
exports.Calculation = Calculation;
exports.Selection_sort = Selection_sort;
exports.Binary_search = Binary_search;
/* No side effect */
