// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Belt_List = require("bs-platform/lib/js/belt_List.js");

var temperaturesData = /* :: */[
  /* tuple */[
    12.5,
    30
  ],
  /* :: */[
    /* tuple */[
      13.7,
      35
    ],
    /* :: */[
      /* tuple */[
        13.2,
        32
      ],
      /* :: */[
        /* tuple */[
          13.7,
          35
        ],
        /* [] */0
      ]
    ]
  ]
];

function calculateTemperature(param) {
  return param[0] - (100.0 - param[1] / 5.0);
}

var result = Belt_List.map(temperaturesData, calculateTemperature);

console.log(result);

exports.temperaturesData = temperaturesData;
exports.calculateTemperature = calculateTemperature;
exports.result = result;
/* result Not a pure module */
