// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function myMap(optValue, f) {
  if (optValue !== undefined) {
    return Caml_option.some(Curry._1(f, Caml_option.valFromOption(optValue)));
  }
  
}

function myFlatMap(optValue, f) {
  if (optValue !== undefined) {
    return Curry._1(f, Caml_option.valFromOption(optValue));
  }
  
}

exports.myMap = myMap;
exports.myFlatMap = myFlatMap;
/* No side effect */
