// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");

function stringOfColorSpec(cspec) {
  if (typeof cspec === "number") {
    if (cspec === 0) {
      return "#ffffff";
    } else {
      return "#000000";
    }
  } else if (cspec.tag) {
    return " rgb(" + (String(cspec[0]) + (", " + (String(cspec[1]) + (", " + (String(cspec[2]) + ") ")))));
  } else {
    return " rgb(32, 23, " + (String(cspec[0]) + ") ");
  }
}

var color1 = /* White */0;

var color2 = /* Black */1;

var color3 = /* Gray */Block.__(0, [0.50]);

var color4 = /* RGB */Block.__(1, [
    255,
    255,
    255
  ]);

exports.color1 = color1;
exports.color2 = color2;
exports.color3 = color3;
exports.color4 = color4;
exports.stringOfColorSpec = stringOfColorSpec;
/* No side effect */
